version: '3'
services:
  node:
    container_name: node
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'